
# This is the configuration used to check the rubocop source code.

# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'package/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.2
  
Documentation:
  Enabled: false




Style/IfUnlessModifier:
  MaxLineLength: 120
Style/WhileUntilModifier:
  MaxLineLength: 120
Metrics/LineLength:
  Max: 120
